name: larapush
description: LaraPush Flutter plugin for push notifications
version: 1.0.0
homepage: https://github.com/dhirajabrandzzy/larapush-android-sdk

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: io.larapush.flutter
        pluginClass: LaraPushPlugin